TARGET_ARCH_VARIANT := x86-atom
TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_GPU_DRIVERS := i915
BOARD_USES_DRM := true
BUILD_WITH_MPLAYER := true
BOARD_HAVE_BLUETOOTH := true
BOARD_USES_S103T_SENSOR := true

include $(GENERIC_X86_CONFIG_MK)
