TARGET_ARCH_VARIANT := x86-atom
TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_GPU_DRIVERS := i915
BOARD_USES_DRM := true
BUILD_WITH_MPLAYER := true
BOARD_HAVE_BLUETOOTH := true
BOARD_USES_S103T_SENSOR := true
BOARD_USES_ALSA_AUDIO := true
BUILD_EMULATOR_CAMERA_HAL := false
BUILD_EMULATOR_SENSORS_MODULE := false

include $(GENERIC_X86_CONFIG_MK)
